### ISSUE TITLE
Problem with Spring boot 2.7.8

### ISSUE THREAD

**Issue by branislavzelenak** [kasramp/Spring-Data-ElasticSearch-Example#3]
Hello,

I tried using your example of test container usage for elastic search, in my project which uses SB 2.7.8.

I ran into a problem when executing spring boot test (integration test) getting "Connection closed exception". 
I also get the same exception when upgrading your project to use spring boot starter parent 2.7.8, and then doing necessary changes due to different versions.

Do you have idea how to solve the problem?

Overall there seem to be issues on how to setup spring boot test with testcontainers for ES and SpringBoot 2.7.8.

**Comment by branislavzelenak** [comment]
^^ forgot to mention I am using latest ES 8.6.2, also in tests.

**Comment by kasramp** [comment]
Hi
I have to test it, the repository has been updated in a while. Currently, I don't have any clue what could be the issue

**Comment by kasramp** [comment]
@branislavzelenak - the max supported version of ES for Spring Boot 2.7.X is 7.17.3, [here](https://docs.spring.io/spring-data/elasticsearch/docs/current/reference/html/#preface.versions]. If you wanna use ES 8.6 and above, max ES 8.7.0, you need to use Spring Boot 3.1.x instead.
You can check the master branch that now uses Spring Boot 3.1.0 with ES 8.7.0

**Comment by branislavzelenak** [comment]
Thanks
